print("### 3 Sayıyı Çarpma ###")
a = int(input("Birinci sayıyı giriniz: "))
b = int(input("İkinci sayıyı giriniz: "))
c = int(input("Üçüncü sayıyı giriniz: "))
print("\n{}, {} ve {} sayısının çarpımı: {}".format(a,b,c,a*b*c))